spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:file:./data/fileDb
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

