#spring:
# h2:
#   console:
#     enabled: 'true'
#     path: /h2-console
# datasource:
#   username: sa
#   url: jdbc:h2:file:./data/fileDb
#   driverClassName: org.h2.Driver
#   password: ''
# jpa:
#   hibernate:
#     ddl-auto: update

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name: false
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
